# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/contructure/contructure.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure || ORIG_REF_NAME==contructure}]

# IP: bd/contructure/ip/contructure_predPC_0_0/contructure_predPC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_predPC_0_0 || ORIG_REF_NAME==contructure_predPC_0_0}]

# IP: bd/contructure/ip/contructure_selectPC_0_0/contructure_selectPC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_selectPC_0_0 || ORIG_REF_NAME==contructure_selectPC_0_0}]

# IP: bd/contructure/ip/contructure_introduction_memory_0_1/contructure_introduction_memory_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_introduction_memory_0_1 || ORIG_REF_NAME==contructure_introduction_memory_0_1}]

# IP: bd/contructure/ip/contructure_predictPC_0_0/contructure_predictPC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_predictPC_0_0 || ORIG_REF_NAME==contructure_predictPC_0_0}]

# IP: bd/contructure/ip/contructure_Split_0_0/contructure_Split_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_Split_0_0 || ORIG_REF_NAME==contructure_Split_0_0}]

# IP: bd/contructure/ip/contructure_decodeReg_0_1/contructure_decodeReg_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_decodeReg_0_1 || ORIG_REF_NAME==contructure_decodeReg_0_1}]

# IP: bd/contructure/ip/contructure_regFile_0_1/contructure_regFile_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_regFile_0_1 || ORIG_REF_NAME==contructure_regFile_0_1}]

# IP: bd/contructure/ip/contructure_addPC_0_0/contructure_addPC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_addPC_0_0 || ORIG_REF_NAME==contructure_addPC_0_0}]

# IP: bd/contructure/ip/contructure_setRegIO_0_0/contructure_setRegIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_setRegIO_0_0 || ORIG_REF_NAME==contructure_setRegIO_0_0}]

# IP: bd/contructure/ip/contructure_decode_0_2/contructure_decode_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_decode_0_2 || ORIG_REF_NAME==contructure_decode_0_2}]

# IP: bd/contructure/ip/contructure_EReg_0_0/contructure_EReg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_EReg_0_0 || ORIG_REF_NAME==contructure_EReg_0_0}]

# IP: bd/contructure/ip/contructure_ALU_A_0_0/contructure_ALU_A_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_ALU_A_0_0 || ORIG_REF_NAME==contructure_ALU_A_0_0}]

# IP: bd/contructure/ip/contructure_ALU_B_0_0/contructure_ALU_B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_ALU_B_0_0 || ORIG_REF_NAME==contructure_ALU_B_0_0}]

# IP: bd/contructure/ip/contructure_ALU_0_0/contructure_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_ALU_0_0 || ORIG_REF_NAME==contructure_ALU_0_0}]

# IP: bd/contructure/ip/contructure_alufun_0_0/contructure_alufun_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_alufun_0_0 || ORIG_REF_NAME==contructure_alufun_0_0}]

# IP: bd/contructure/ip/contructure_MREG_0_0/contructure_MREG_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_MREG_0_0 || ORIG_REF_NAME==contructure_MREG_0_0}]

# IP: bd/contructure/ip/contructure_CCREG_0_0/contructure_CCREG_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_CCREG_0_0 || ORIG_REF_NAME==contructure_CCREG_0_0}]

# IP: bd/contructure/ip/contructure_cond_0_0/contructure_cond_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_cond_0_0 || ORIG_REF_NAME==contructure_cond_0_0}]

# IP: bd/contructure/ip/contructure_WREG_0_0/contructure_WREG_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_WREG_0_0 || ORIG_REF_NAME==contructure_WREG_0_0}]

# IP: bd/contructure/ip/contructure_memOperation_0_0/contructure_memOperation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_memOperation_0_0 || ORIG_REF_NAME==contructure_memOperation_0_0}]

# IP: bd/contructure/ip/contructure_data_memory_0_1/contructure_data_memory_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==contructure_data_memory_0_1 || ORIG_REF_NAME==contructure_data_memory_0_1}]

# XDC: bd/contructure/contructure_ooc.xdc
